import { Developer } from "@/types";

export const mockDevelopers: Developer[] = [
  {
    id: 1,
    name: "Sarah Chen",
    username: "sarahdev",
    title: "Senior Frontend Engineer",
    reputation: 45672,
    badges: { gold: 12, silver: 45, bronze: 128 },
    tags: ["react", "typescript", "next.js"],
    avatar: "/avatars/sarah.jpg",
    answersCount: 1247,
    questionsCount: 89,
    location: "San Francisco, CA",
  },
  {
    id: 2,
    name: "Alex Rodriguez",
    username: "alexcode",
    title: "Full Stack Developer",
    reputation: 32104,
    badges: { gold: 8, silver: 34, bronze: 95 },
    tags: ["python", "django", "react"],
    avatar: "/avatars/alex.jpg",
    answersCount: 892,
    questionsCount: 156,
    location: "New York, NY",
  },
  {
    id: 3,
    name: "Jordan Kim",
    username: "jordank",
    title: "Backend Engineer",
    reputation: 28956,
    badges: { gold: 6, silver: 28, bronze: 76 },
    tags: ["node.js", "mongodb", "aws"],
    avatar: "/avatars/jordan.jpg",
    answersCount: 743,
    questionsCount: 234,
    location: "Seattle, WA",
  },
  {
    id: 4,
    name: "Jordan Kim",
    username: "jordank",
    title: "Backend Engineer",
    reputation: 28956,
    badges: { gold: 6, silver: 28, bronze: 76 },
    tags: ["node.js", "mongodb", "aws"],
    avatar: "/avatars/jordan.jpg",
    answersCount: 743,
    questionsCount: 234,
    location: "Seattle, WA",
  },
];
