export const trendingTags = ["JavaScript", "Python", "React", "UI/UX", "Node.js", "TypeScript"];

export const blogPosts = [
  "Robots in the skies (and they use Transformer models)",
  "Research roadmap update, August 2025"
];

export const metaPosts = [
  "Policy: Generative AI (e.g., ChatGPT) is banned",
  "Updated design for the new live activity panel experiment", 
  "Further Experimentation with Comment Reputation Requirements"
];

export const hotPosts = [
  "What is the standard for attribution for code generated by AI?"
];